### ISSUE TITLE
SOFA scores calculation in eICU

### ISSUE THREAD

**Issue by ZiyueC** [eth-mds/ricu#12]
Dear ricu team, I am curious about how do you calculate the sofa components scores for the eICU database?

Looks like there is no valid method and derived table for eICU Sofa score calculation.

**Comment by dplecko** [comment]
This is certainly overdue, but in case it still matters, or interests someone else, here is an answer.

The code for computing `sofa` is shared across all data sources in `ricu`, in a concept `sofa`. To inspect the concept, you can run 

```
> get_config("concept-dict")[["sofa"]]
$concepts
[1] "sofa_resp"   "sofa_coag"   "sofa_liver"  "sofa_cardio" "sofa_cns"   
[6] "sofa_renal"
```

to see the subconcepts upon `sofa` is built (SOFA score is constructed using the function `sofa_score`, see `?sofa_score` for more information and the docs). Therefore, we need to check what `sofa_resp` etc. call, by running

```
> get_config("concept-dict")[["sofa_resp"]]
$concepts
[1] "pafi"     "vent_ind"
```

so the respiratory component calls `pafi` (PaO2/FiO2 ratio) and `vent_ind`.  Further, `pafi` consists of

```
> get_config("concept-dict")[["pafi"]]
$concepts
[1] "po2"  "fio2"
```

and to check how these are loaded in `eICU` you can simply look at `"sources"`, `"eicu"` entry, e.g.,

```
> get_config("concept-dict")[["po2"]][["sources"]][["eicu"]]
[[1]]
[[1]]$ids
[1] "paO2"

[[1]]$table
[1] "lab"

[[1]]$sub_var
[1] "labname"
```

Therefore, `po2` is loaded from the `lab` table, loading rows where the `labname` column matches the string `"paO2"`. Other parts of the SOFA computation you are interested in can be checked similarly. Let me know if there is anything else.
