### ISSUE TITLE
Discrepancies with preprint numbers

### ISSUE THREAD

**Issue by prockenschaub** [eth-mds/ricu#14]
### Problem 

I am trying to replicate the MIMIC III numbers given in the preprint [Moor et al. (2021)](https://arxiv.org/pdf/2107.05230.pdf), which relies on this package for preprocessing. Unfortunately, I am unable to replicate their reported patient attrition (Extended Data Figure 1) and the overlap between different definitions of suspected infection (Supplementary Figure 14). 

I appreciate that this question isn't necessarily directly related to `ricu` but belongs to the paper repo. However, that repo unfortunately isn't public yet. Since there is an overlap in authors @nbenn , I hoped to get some early help here. 

#### Patient attrition

Let's start with patient attrition. I start with the same number of patients in MIMIC III and remove the same number of patients due to age < 14 years, leaving me with 53,432 patients. 

```r
nrow(load_id(mimic$icustays))
#> [1] 61532

load_concepts("age", src = "mimic", verbose = FALSE) %>% 
   filter(age < 14) %>%
   nrow()
#> [1] 8100
```

However, that's when the agreement stops. Moving on to the requirement of sepsis onset in the ICU, I get a lower number of exclusions when filtering for sepsis cases inside the ICU:

```r
load_concepts("sep3", src = "mimic", verbose = FALSE) %>% 
  inner_join(icustays_adults, by = "icustay_id") %>%  # icustays_adults == load_id(mimic$icustays) with age >= 14
  filter(charttime < intime | outtime < charttime)
#> [1] 3062
```

This misses almost 2,000 patients that were excluded in the preprint. I played around with different definitions of "inside the ICU" but to no avail. Checking for sepsis onset between the 4th and 168th hour also returns a lower than reported number at 10,051

```r
load_concepts("sep3", src = "mimic", verbose = FALSE) %>% 
  semi_join(icustays_inside, by = "icustay_id") %>% # icustays_inside== icustays_adults without  sepsis < intime or outtime < sepsis
  filter(charttime < 4 | charttime > 168)
```

There are also some discrepancies with the remaining exclusion criteria but those are lesser and I am unsure whether this is just because I messed up the previous exclusions. As a side note, the total number of exclusions `8100+4861+10359+486+472+681=24959` mentioned in the paper also does not agree with the final cohort size of `36591` (`61532-24959=36573`).

#### Suspicion of infection

Similar to the above, I arrive at different numbers when attempting to replicate the Venn diagram in Supplementary Figure 14. According to the diagram, there should be `8652+23556=32208` ICU stays with antibiotics and fluid sampling according to Sepsis-3 criteria in the dataset. As far as I understand, this is implemented in the `susp_inf` concept. However, loading this concept gives 

```r
load_concepts("susp_inf", src = "mimic", verbose = FALSE) %>% 
   distinct(icustay_id) %>% 
   nrow()
#> [1] 31070
```

Obtaining the multi-Abx subset `1844+23556=25400` is further complicated by the fact that the preprint does not specify what `abx_min_count` and `abx_count_win` were used. Assuming `abx_min_count=2` and `abx_count_win=hours(24L)`, we get 

```r
ricu::susp_inf(
        list(abx = abx, samp = samp),
        si_mode = "abx",
        abx_min_count = 2,
        abx_count_win = hours(24L),
    ) %>% 
   filter(susp-inf) %>% 
   distinct(icustay_id) %>%
   nrow()
#> [1] 21481
```

This is again smaller than what we find in the preprint. Expanding the timeframe to `abx_count_win=hours(48L)`, we get a closer matching but still lower number at 23,243.

### Question 

I appreciate how hard it is to present full replication when working with EHR data and complicated definitions such as Sepsis-3. I'd be grateful for any suggestions as to where I might be going wrong or what might explain the above differences.

**Comment by dplecko** [comment]
@prockenschaub please let me know if this is still of interest.
