### ISSUE TITLE
Release of MIMIC IV version 2.0 and database versioning

### ISSUE THREAD

**Issue by prockenschaub** [eth-mds/ricu#15]
Version 2.0 of MIMIC IV was released on June 12th 2022: https://physionet.org/content/mimiciv/2.0/

### Problems

So far, this new version has led to the following issues for me:

1. Warning messages related to the expected number of rows, e.g.:
```r
# 1: expected 523740 rows but got 454324 rows for table `admissions` 
```
2. Omission of the tables `admissions`, `patients`, and `transfers` when running `import_src('miiv')`, as they have been moved from the core module into the hosp module and are thus not recognised.

### Question
A quick fix for this is updating the row numbers and paths in the config file. 

However, this raises a bigger point about whether `ricu` should allow for versioning of databases:

- In its simplest form, this can be solved with a separate config file for each version (with the latest version as the default). 
- If concepts/items become available or cease to exist in a newer version, this would also require to version concepts. A sensible default here could be to treat concepts without version info to apply to every version of the database (thus making every currently available concept available by default) and only apply versioning if a concept is actively marked as only being available for certain versions.

**Comment by dplecko** [comment]
Thanks for the suggestion; `ricu 0.6.0` bumps `miiv` to `v2.2`, which should fix some of this stuff. Skipping dataset versioning for now (it is a major effort at this stage).
