### ISSUE TITLE
How to cite? 

### ISSUE THREAD

**Issue by Zethson** [eth-mds/ricu#27]
Hi,

I'd like to cite ricu. I couldn't find an associated paper or any other associated DOI. Did I miss it? if not, could you please add one using for example zenodo? Cheers

**Comment by prockenschaub** [comment]
You should be able to cite the arXiv paper: https://arxiv.org/pdf/2108.00796.pdf

**Comment by dplecko** [comment]
Hi,

The `ricu` paper is now published in GigaScience, and the correct citation is:
```
@article{bennett2023ricu,
  title={ricu: R’s interface to intensive care data},
  author={Bennett, Nicolas and Ple{\v{c}}ko, Drago and Ukor, Ida-Fong and Meinshausen, Nicolai and B{\"u}hlmann, Peter},
  journal={GigaScience},
  volume={12},
  pages={giad041},
  year={2023},
  publisher={Oxford University Press}
}
```
