### ISSUE TITLE
CSV datafiles are already downloaded how to connect with ricu package (Windows)

### ISSUE THREAD

**Issue by royarkaprava** [eth-mds/ricu#3]
First all, great package. I have already downloaded all the data for Physionet as compressed csv files for MIMIC III and also IV. But, I am finding it very hard to let ricu know that where they are located. I tried "load_src_cfg" to configure my csv files by passing the folder link of all the files. That did not work. I can redownload all the files if that simplifes everything and automatically connected to the package. I could not understand that part also, what function to use to re-download all the files, how the credentials to be provided, how to let the function know which data I want to download.

-Arkaprava

**Comment by royarkaprava** [comment]
I set
Sys.setenv(RICU_SRC_LOAD = "location of the folder containing all the 26 csv files of MIMIC III")

then I did library(ricu). It says "0 of NA tables available"

**Comment by royarkaprava** [comment]
I got this now after multiple trial and errors. I am now struggling to run the sofa score related functions. I will try a bit more. Otherwise raise an issue on that.

**Comment by anothersin** [comment]
> I got this now after multiple trial and errors. I am now struggling to run the sofa score related functions. I will try a bit more. Otherwise raise an issue on that.

Hi Arkaprava,

I am experiencing the same problem, would you mind giving any help on how you solved it.

**Comment by royarkaprava** [comment]
> 

I told some of my friends to follow these steps. Note that I downloaded the mimic data files from the physionet. Or there is download option in ricu. I think it is download_src() and import_src(). Using these packages is better.

Install ricu.
library(ricu)
run data_dir() which will give you folder name.
Navigate and go inside that folder (which should be empty) and save the data file folder.
Then close and open R and library(ricu) again. Now it should show mimic or miiv ticked (whichever you downloaded).
