### ISSUE TITLE
Error opening MIMIC IV

### ISSUE THREAD

**Issue by Shaydund** [eth-mds/ricu#33]
I have an error opening MIMIC IV using RICU package. 

The code i'm writting is the next:

> remotes::install_github("eth-mds/ricu", dependencies = TRUE)

> Sys.setenv(RICU_PHYSIONET_USER = "xxxxxx" , 
           RICU_PHYSIONET_PASS = "xxxxxxx")
> library(ricu)
> download_src("miiv") 

Error in `stop_ricu()`:
! Access to the requested resource was denied. Please set up an
account at https://physionet.org/ and apply for data access.
Backtrace:
  1. ricu::download_src("miiv")
  2. ricu:::download_src.character("miiv")
  3. base::Map(...)
  4. base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
  6. ricu:::download_src.src_cfg(...)
  7. ricu:::download_check_data(...)
  8. ricu:::get_sha256(url, user, pass)
  9. ricu:::download_pysionet_file(...)
 10. ricu:::stop_ricu(...)
 
 
###########################################
###########################################

I don't have problems with eicu_demo and mimic_demo.
I have the credentials of mimic IV 
My computer pass the requirements. 

Sure i'm doing something (stupid) wrong

**Comment by mlondschien** [comment]
See [here](https://github.com/eth-mds/ricu/issues/28#issuecomment-1535828282).

**Comment by dplecko** [comment]
MIMIC-IV (`miiv` in `ricu`) was bumped to `v2.2` in `ricu 0.6.0`. It should solve the issue. If problems persist, feel free to open a new issue.
