### ISSUE TITLE
Finding dosage treatments for patients in MIMIC-III

### ISSUE THREAD

**Issue by pshuwei** [eth-mds/ricu#34]
Hi, I'm a doctoral student interested using this database. 

My PI and I are particularly interested in looking at different treatments for patients, and in particular those treatments should have different dosages. 

Does the ricu/mimic-iii data have anything on that?

Thanks!

**Comment by dplecko** [comment]
Hi,

Thanks for the question. There is a number of different treatments in the ICU that have varying dosages. For example, you can consider treatment with insulin (`ricu` concept `ins`) which is given for lowering glucose levels. Another commonly used class of drugs in the ICU are vasopressors which are used e.g. for patients with cardiogenic shock. In `ricu`, the common concepts for this are `norepi_rate`, `epi_rate`, `dobu_rate`, `dopa_rate`, which are reported across a number of datasets.

Good luck exploring!
