### ISSUE TITLE
Strange error when I download miiv dataset

### ISSUE THREAD

**Issue by PolarisMyself** [eth-mds/ricu#42]
**Description:**
I am encountering an unusual error while attempting to download the miiv dataset. The error message I am receiving is as follows:

```
Error in `assert_that()`:
! core/omr.csv.gz was not found among the provided options. Did you
possibly mean hosp/drgcodes.csv.gz instead?
```
**Code Snippet:**
Here is the relevant code snippet that is causing the error:

```
admissions_df <- as.data.frame(miiv$admissions)
icustays_df <- as.data.frame(miiv$icustays)
patients_df <- as.data.frame(miiv$patients)
```
**Issue Background:**
I have tried to use the above code to download the miiv dataset, but I am consistently encountering this error. Strangely, I have successfully used a similar approach to download the MIMIC III dataset without any issues.

**Question:**
Could this error possibly be caused by a version difference in the miiv dataset compared to MIMIC III? I am using the latest versions of the packages and libraries, but this issue persists.

**Request for Assistance:**
I am new to R, and I find it difficult for me to solve the error by reading source code. I would greatly appreciate any guidance or insights regarding this error. If anyone has encountered a similar problem or has suggestions on how to resolve it, please share your thoughts.

Thank you for your help!

**Comment by dplecko** [comment]
In `ricu 0.6.0`, this should be resolved since MIMIC-IV version was bumped to `2.2`. If the problem still persists, please open a new issue, and I will be happy to have a look.
