### ISSUE TITLE
Memory Requirement of Importing MIMIC-IV

### ISSUE THREAD

**Issue by oezyurty** [eth-mds/ricu#5]
Hi, 

In section 5 of vignette https://cran.r-project.org/web/packages/ricu/vignettes/jss.pdf , it is written that memory requirements are kept low around 8-16 GB. 

However, when I am importing MIMIC-IV on my laptop with 16 GB memory, my R session was terminated due to insufficient memory. 

Later, I could only import MIMIC-IV on another device where the process used ~30 GB memory at peak time. 

I just wanted to confirm if this is an expected behavior. If yes, maybe you can update the vignette in that regard. 

Best,

**Comment by nbenn** [comment]
Thanks for pointing this out. You're right, at the time when this was written, MIMIC-IV was not yet included with ricu, so in principle it is possible that MIMIC-IV increases the memory ceiling. At the same time, most memory intensive steps are implemented in a chunked fashion (for all datasets), so this comes as a bit of a surprise to me. At some time, the readr package had a memory leak. Do you by any chance know what readr version you're using? Also, do you recall in which step you ran out of memory?

**Comment by oezyurty** [comment]
Hi, thanks for the quick reply! 

I now checked that readr version was 2.1.1 . 

I don't know the exact step (in the background) I ran out of memory. What I remember is that all table are downloaded successfully, then it started importing the files. Then I couldn't see any progress report printed out the console, and R session died.

**Comment by dplecko** [comment]
@oezyurty please feel free to open a new issue if this problem still requires attention. I am closing this one for now since it's old.
